### ISSUE TITLE
[Ubuntu 14.04] Segmentation fault on hrender

### ISSUE THREAD

**Issue by siriusxiv** [avr-aics-riken/HIVE#9]
I noticed a segmentation fault error on hrender. This error does not happen on Mac OS X with the same input but happens on my Linux machine.

The gdb error report is:

```
(gdb) set args scene.scn

(gdb) r
Program received signal SIGSEGV, Segmentation fault.
_IO_fgets (buf=0x7fffffffcb60 "lsgl_shader_source_BC41mx", n=4095, fp=0x7fffffffcb60) at iofgets.c:50
50  iofgets.c: No such file or directory.

(gdb) bt
#0  _IO_fgets (buf=0x7fffffffcb60 "lsgl_shader_source_BC41mx", n=4095, fp=0x7fffffffcb60) at iofgets.c:50
#1  0x00007ffff7944a7e in lsgl::FragmentShader::DoCompile() () from /home/malik/workspace/riken/HIVE/build/bin/libLSGLES.so.0
#2  0x00007ffff794420a in lsgl::Shader::Compile() () from /home/malik/workspace/riken/HIVE/build/bin/libLSGLES.so.0
#3  0x000000000045ad54 in CreateProgramSrc_SGL(char const*, unsigned int&) ()
#4  0x000000000045d519 in VolumeBuffer::Create(VolumeModel const*) ()
#5  0x000000000045f5cf in RenderCore::Render() ()
#6  0x0000000000462505 in render(lua_State*) ()
#7  0x00007ffff7bae980 in luaD_precall () from /home/malik/workspace/riken/HIVE/build/bin/liblua.so
#8  0x00007ffff7bbe574 in luaV_execute () from /home/malik/workspace/riken/HIVE/build/bin/liblua.so
#9  0x00007ffff7baefc9 in luaD_call () from /home/malik/workspace/riken/HIVE/build/bin/liblua.so
#10 0x00007ffff7bae1ac in luaD_rawrunprotected () from /home/malik/workspace/riken/HIVE/build/bin/liblua.so
#11 0x00007ffff7baf301 in luaD_pcall () from /home/malik/workspace/riken/HIVE/build/bin/liblua.so
#12 0x00007ffff7ba782a in lua_pcallk () from /home/malik/workspace/riken/HIVE/build/bin/liblua.so
#13 0x0000000000462387 in SceneScript::Execute(char const*) ()
#14 0x000000000041ed37 in renderScene(char const*) ()
#15 0x000000000041eb4e in main ()
```

You can get the files to reproduce the bug here:
https://github.com/siriusxiv/RandomFiles/tree/master/segfault

**Comment by syoyo** [comment]
I found seg fault due to invalid access to array when there's NaN value in input volume data, and fixed it in this commit.

https://github.com/avr-aics-riken/HIVE/commit/7ccdc560bd7cf48a436526b61209b83e03c7db93

Please pull recent HIVE and build hrender. I guess it solves this issue also.

**Comment by siriusxiv** [comment]
Indeed, the issue was solved with my test data. Well done!
